import { globSync } from 'glob';
import { mkdirSync, writeFileSync } from 'node:fs';
import { relative } from 'node:path';

const GENERATED_DIR = 'src/_generated';
const OUTPUT_FILE = `${GENERATED_DIR}/topics.ts`;

mkdirSync(GENERATED_DIR, { recursive: true });

const files = globSync('content/*/*/v*.ts').sort();

if (files.length === 0) {
  console.warn('[codegen] No topics found matching content/*/*/v*.ts');
}

const imports = files
  .map((file, i) => {
    const importPath = relative(GENERATED_DIR, file).replace(/\.ts$/, '');
    const normalized = importPath.startsWith('.') ? importPath : `./${importPath}`;
    return `import { data as t${i} } from '${normalized}';`;
  })
  .join('\n');

const list = files.map((_, i) => `t${i}`).join(', ');

const banner = '// AUTO-GENERATED by scripts/codegen-topics.ts — do not edit by hand.';

const contents = `${banner}
import type { TopicMetadata } from '../types/content';

${imports}

export const allTopics: readonly TopicMetadata[] = [${list}];
`;

writeFileSync(OUTPUT_FILE, contents);
console.log(`[codegen] Wrote ${OUTPUT_FILE} with ${files.length} topic(s).`);
