import type { BgMusicMood } from "./types/content";

/**
 * One entry of the music manifest (generated by `scripts/fetch-music.ts`).
 * `file` is a path relative to `public/`.
 */
export type MusicEntry = {
  mood: string;
  file: string;
  recordingId: string;
  title: string;
  /** true when the track was trimmed to the exact video length via EditRecording. */
  exact?: boolean;
};

export type MusicManifest = Record<string, MusicEntry>;

/** Mood used for any topic that does not set its own `bgMusicMood`. */
export const DEFAULT_BG_MUSIC_MOOD: BgMusicMood = "lo-fi-hip-hop";

/**
 * Maps each mood to a real Epidemic Sound genre taxonomy slug. Free-text `searchTerm` is
 * ignored by the catalog, so `fetch-music` filters by `taxonomySlugs` (verified to exist via
 * scripts/spike-genre-filter.ts).
 */
export const MOOD_TAXONOMY: Record<BgMusicMood, string> = {
  "lo-fi-hip-hop": "lo-fi-hip-hop",
  "lofi-house": "lo-fi-house",
  "ambient-tech": "ambient",
  "synthwave-cyberpunk": "synthwave",
};

/** Volume for per-topic background music (low, so it sits under narration). */
export const TOPIC_MUSIC_VOLUME = 0.07;

/** Manifest key for a topic: `<category>--<id>--<version>`. */
export const topicKey = (category: string, id: string, version: string) =>
  `${category}--${id}--${version}`;
